Warehouse.WebUI/Controllers/DeliveryController.cs
using System;
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;
using Warehouse.Domain.Abstract;
using Warehouse.Domain.Entities;
using Warehouse.WebUI.Models;
using Warehouse.WebUI.Security;
using Warehouse.WebUI.Services.Delivery;

namespace Warehouse.WebUI.Controllers
{
    [Authorize]
    [SessionTimeout]
    public class DeliveryController : Controller
    {
        private readonly DeliveryService _deliveryService;

        public DeliveryController(IRepository<Delivery> deliveryRepository, IRepository<Order> orderRepository, IRepository<DeliveryType> deliveryTypeRepository, IRepository<Address> addressRepository)
        {
            _deliveryService = new DeliveryService(deliveryRepository,orderRepository,deliveryTypeRepository,addressRepository);
        }

        [HttpGet]
        public ActionResult ChooseDelivery(int idOrder)
        {
            if (_deliveryService.CheckIfWasDone(idOrder))
                return RedirectToAction("List", "Order");

            ViewBag.DeliveryTypes = 
                GetDeliveryTypesList(_deliveryService.GetTypesOfDelivery());
            var model = _deliveryService.GetDeliveryAddressVM(idOrder, "SelectedType");
            
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SetDelivery(DeliveryAddressViewModel deliveryAddress)
        {
            if (!ModelState.IsValid)
                return View("ChooseDelivery");

            AddDelivery(deliveryAddress);
            return RedirectToAction("List", "Order");
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            if (_deliveryService.CheckIfOrderHasDelivery(id.Value))
                return View(_deliveryService.GetDeliveryTypeVM(id.Value));

            return RedirectToAction("List","Order");
        }

        private void AddDelivery(DeliveryAddressViewModel deliveryAddress)
        {
            var delivery = deliveryAddress.Delivery;
            delivery.DeliveryTypeId = Int32.Parse(deliveryAddress.SelectedType);
            var address = deliveryAddress.Address;

            if (_deliveryService.CheckIfAddressExist(address))
            {
                delivery.AddressId =
                    _deliveryService.GetIdAddressIfExists(address).Value;
                _deliveryService.AddDeliveryToDb(delivery);
            }
            else
            {
                _deliveryService.AddAddressToDb(address);
                delivery.AddressId = _deliveryService.GetIdAddressIfExists(address).Value;
                _deliveryService.AddDeliveryToDb(delivery);
            }

            _deliveryService.UpdateOrder
                (deliveryAddress.IdOrder, delivery.Id, delivery.DeliveryTypeId);
        }

        private SelectList GetDeliveryTypesList(IEnumerable<DeliveryType> deliveryTypes)
        {
            return new SelectList(deliveryTypes,"Id","FullInfo", "Payment",1);
        }
    }
}

Warehouse.WebUI/Controllers/DeliveryTypeController.cs
using System.Linq;
using System.Web.Mvc;
using Warehouse.Domain.Abstract;
using Warehouse.Domain.Entities;

namespace Warehouse.WebUI.Controllers
{
    public class DeliveryTypeController : Controller
    {
        private IRepository<DeliveryType> _deliveryRepository;

        public DeliveryTypeController(IRepository<DeliveryType> deliveryRepository)
        {
            _deliveryRepository = deliveryRepository;
        }

        [HttpGet]
        public ActionResult InformationAboutDelivery()
        {
            var deliveryTypes = _deliveryRepository.Get().ToList();
            return View(deliveryTypes);
        }
    }
}

Warehouse.WebUI/Controllers/ProductCategoryController.cs
using System.Web.Mvc;
using Warehouse.Domain.Abstract;
using Warehouse.Domain.Entities;
using Warehouse.WebUI.Services.ProductCategory;

namespace Warehouse.WebUI.Controllers
{
    public class ProductCategoryController : Controller
    {
        private ProductCategoryService _productCategoryService;

        public ProductCategoryController(IRepository<ProductCategory> productCategoryRepository)
        {
            _productCategoryService = new ProductCategoryService(productCategoryRepository);
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            var categories = _productCategoryService.GetProductCategories();
            return PartialView(categories);
        }
    }
}

Warehouse.WebUI/Controllers/ProductController.cs
using System.IO;
using System.Web;
using System.Web.Mvc;
using Warehouse.Domain.Abstract;
using Warehouse.Domain.Entities;
using Warehouse.WebUI.Models.Pagination;
using Warehouse.WebUI.Security;
using Warehouse.WebUI.Services.Product;

namespace Warehouse.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private PagginationService _pagginationService;
        private ProductService _productService;

        public ProductController(IRepository<Product> productRepository, IRepository<ProductDetails> productDetails)
        {
            _pagginationService = new PagginationService(productRepository);
            _productService = new ProductService(productRepository,productDetails);
        }

        [HttpGet]
        [Authorize]
        public ActionResult SearchProductsForOrder(string phrase)
        {
            var model = _pagginationService.GetSearchedModel(1, 10, phrase);
            return View("ShowProducts", model);
        }

        [HttpGet]
        public ActionResult SearchProducts(string phrase)
        {
            var model = _pagginationService.GetSearchedModel(1, 10, phrase);
            return View("List", model);
        }

        [HttpGet]
        public ActionResult List(string category,int page = 1, int pageSize = 10)
        {
            EntitiesListViewModel<Product> model = _pagginationService.GetPagginationModel(page, pageSize, category);
            return View(model);
        }

        [HttpGet]
        [SessionTimeout]
        [Authorize]
        public ActionResult AddProduct()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        [SessionTimeout]
        public ActionResult AddProduct(Product product, HttpPostedFileBase file)
        {
            ValidateFile(file);
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    AddProductWithImage(product,file);
                    ShowCorrectMessage();
                }
                else
                {
                    _productService.AddProductToDb(product);
                    ShowCorrectMessage();
                }
                
            }
            return View();
        }

        [HttpGet]
        public ActionResult ProductInfo(int id)
        {
            Product product =  _productService.GetProduct(id);
            if (!CheckCorrectnessProduct(product))
                return RedirectToAction("ShowProducts");
                
            return View(product);
        }

        [HttpGet]
        [Authorize]
        [SessionTimeout]
        public ActionResult ShowProducts(string category,int page = 1, int pageSize = 10)
        {
            EntitiesListViewModel<Product> model =
                _pagginationService.GetPagginationModel(page, pageSize, category);
            _productService.ConnectProductsWithImages(model.Entities);
            return View(model);
        }

        private void AddProductWithImage(Product product, HttpPostedFileBase file)
        {
            _productService.AddProductToDb(product);
            string pathGallery = $"~\\ProductPhotos\\{product.Id}\\";
            CreatePathIfNotExist(pathGallery);

            _productService.SaveFile(file, Path.Combine(Server.MapPath(pathGallery)));
            var productDetails =
                _productService.GetProductDetails(product.Id, pathGallery.Remove(0, 1) + file.FileName);
            _productService.AddProductDetailsToDb(productDetails);
        }

        private void CreatePathIfNotExist(string path) // care about permission
        {
            if (!Directory.Exists(path))
                Directory.CreateDirectory(Server.MapPath(path));
        }

        private void ValidateFile(HttpPostedFileBase file)
        {
            if (!_productService.ValidateTypeFile(file))
            {
                ModelState.AddModelError("WrongExtesionOfFile",
                    @"Nie obsługiwany typ pliku! Pliki graficzne są tylko możliwe do przesłania");
            }
            if (!_productService.ValidateSizeFile(file))
            {
                ViewBag.MaxSizeFilekB = _productService.MaxSizeOfPictureInkB;
                ModelState.AddModelError("WrongSizeOfFile",
                    $@"Maksymalny dopuszalny rozmiar pliku to {(_productService.MaxSizeOfPictureInMB):##.###}MB");
            }
        }

        private bool CheckCorrectnessProduct(Product product)
        {
            if (product == null)
            {
                TempData["ProductIsNull"] = "Taki produkt nie istnieje!";
                return false;
            }

            return true;
        }

        private void ShowCorrectMessage()
        {
            ModelState.Clear();
            ViewBag.MessageOKAddProduct = "Produkt został zapisany!";
        }
    }
}

Warehouse.WebUI/Views/Shared/OrderSummary.cshtml
@model Warehouse.Domain.Entities.Order

<tr>
    <td>
        @Html.DisplayFor(modelItem => Model.Id)
    </td>
    <td>
        @Html.DisplayFor(modelItem => Model.NetOrderValue)
    </td>
    <td>
        @Html.DisplayFor(modelItem => Model.GrossOrderValue)
    </td>
    <td>
        @Model.OrderDate.ToString("g")
    </td>
    <td>
        @Html.DisplayFor(modelItem => Model.Status)
    </td>
    <td>
        @Html.DisplayFor(modelItem => Model.Payment)
    </td>
    <td>
        <div style="margin-bottom: 3px; float:left">
            @using (Html.BeginForm("Details", "Order", FormMethod.Get))
            {
                <input type="number" name="id" value=@Model.Id hidden="true">
                <input type="submit" value="Szczegóły" class="btn btn-primary" />
            }
        </div>
        @if (Model.DeliveryId != null)
        {
            <div style="margin-left: 5px">
                @using (Html.BeginForm("Details", "Delivery", FormMethod.Get))
                {
                    <input name="id" value=@Model.Id hidden="true">
                    <input type="submit" value="Sprawdź dane dostawy" class="btn" style="background: lawngreen; " />
                }
            </div>
        }

        @if (Model.DeliveryId == null)
        {
            <div style="clear:both">
                @using (Html.BeginForm("ChooseDelivery", "Delivery", FormMethod.Get))
                {
                    <input name="idOrder" value=@Model.Id hidden="true">
                    <input type="submit" value="Określ dostawę" class="btn btn-primary btn-info" />
                }
            </div>
        }
        @if (Model.DeliveryId == null)
        {
            <div style="clear:both">
                @using (Html.BeginForm("Delete", "Order", FormMethod.Post))
                {
                    <input name="id" value=@Model.Id hidden="true">
                    <input type="submit" value="Usuń zamówienie" class="btn btn-primary btn-danger" />
                }
            </div>
        }
    </td>

</tr>

Warehouse.WebUI/Views/Shared/ProductSummary.cshtml
@model Warehouse.Domain.Entities.Product

<div class="well">
    <h3>
        @if (Model.ProductDetailses != null && Model.ProductDetailses.Count > 0)
        {
            @Html.Partial("ShowPicture",Model.ProductDetailses[0].PathPhoto)
        }
        @Html.ActionLink(Model.Name,"ProductInfo","Product",new {id = Model.Id},null)
        
        <span class="pull-right label label-primary">@Model.GetGrossProductValue().ToString("C")</span>
    </h3>

    @using (Html.BeginForm("AddToOrder", "Order"))
    {
        <div class="pull-right">
            @Html.HiddenFor(x => x.Id)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Dodaj do zamówienia" />
        </div>
    }

    <span class="lead">Ilość: @Model.Quantity</span>
</div>

Warehouse.WebUI/Views/Shared/ShowPicture.cshtml
@model string

<a href="@Model">
    <img class="img-thumbnail" src="@Model" width="150" height="150"/>
</a>

Warehouse.WebUI/Views/Shared/_Layout.cshtml
@using Warehouse.WebUI.HtmlHelpers
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Warehouse</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <style>
        .Tlo {
            background-color:beige
        }
        textarea {
            resize: none
        }
    </style>
</head>
<body class="Tlo">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Warehouse", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Request.IsAuthenticated && Session["ClientId"] != null)
                {
                    <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "AddProduct" ? "active" : "")">
                        @Html.ActionLink("Przeglądaj produkty", "List", "Product")
                    </li>
                    <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "ProductInfo" ? "active" : "")">
                        @Html.ActionLink("Złóż zamowienie", "ShowProducts", "Product")
                    </li>
                    <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "List" ? "active" : 
                                     ViewContext.RouteData.Values["Action"].ToString() == "ChooseDelivery" ? "active" : 
                                         ViewContext.RouteData.Values["Action"].ToString() == "Details" ? "active" : "")">
                        @Html.ActionLink("Zamowienia", "List", "Order")
                    </li>
                <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "Checkout" ? "active" : "")">@Html.ActionLink("Koszyk", "Checkout", "Order")</li>
                <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "InformationAboutDelivery" ? "active" : "")">@Html.ActionLink("Dostawa", "InformationAboutDelivery", "DeliveryType")</li>
                <li>@Html.ActionLink("Kontakt", "SendEmailForContact", "Home")</li>
                <li>@Html.ActionLink("Wyloguj", "Logout", "Client")</li>
                }
                else
                {
                <li>@Html.ActionLink("Przeglądaj produkty", "List", "Product")</li>
                <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "InformationAboutDelivery" ? "active" : "")">@Html.ActionLink("Dostawa", "InformationAboutDelivery", "DeliveryType")</li>
                <li>@Html.ActionLink("Kontakt", "SendEmailForContact", "Home")</li>
                <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "Register" ? "active" : "")">@Html.ActionLink("Rejestracja", "Register", "Client")</li>
                <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "Login" ? "active" : "")">@Html.ActionLink("Zaloguj", "Login", "Client")</li>
                }
                </ul>
            </div>
        </div>
    </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year Gontek95</p>
            </footer>
        </div>
</body>
</html>

Warehouse.WebUI/Views/Shared/_LayoutWithCategories.cshtml
@using Warehouse.WebUI.HtmlHelpers
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Warehouse</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <style>
        .Tlo {
            background-color: beige
        }
        textarea {
            resize: none
        }
    </style>
</head>
<body class="Tlo">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Warehouse", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Request.IsAuthenticated && Session["ClientId"] != null)
                    {
                        <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "List" ? "active" : 
                                         ViewContext.RouteData.Values["Action"].ToString() == "SearchProducts" ? "active" : "")">
                            @Html.ActionLink("Przeglądaj produkty", "List", "Product")
                        </li>
                        <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "ShowProducts" ? "active" : 
                                         ViewContext.RouteData.Values["Action"].ToString() == "SearchProductsForOrder" ? "active" : "")">
                            @Html.ActionLink("Złóż zamowienie", "ShowProducts", "Product")
                        </li>
                        <li>@Html.ActionLink("Zamowienia", "List", "Order")</li>
                        <li>@Html.ActionLink("Koszyk", "Checkout", "Order")</li>
                        <li>@Html.ActionLink("Dostawa", "InformationAboutDelivery", "DeliveryType")</li>
                        <li>@Html.ActionLink("Kontakt", "SendEmailForContact", "Home")</li>
                        <li>@Html.ActionLink("Wyloguj", "Logout", "Client")</li>
                    }
                    else
                    {
                        <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "List" ? "active" : 
                                         ViewContext.RouteData.Values["Action"].ToString() == "SearchProducts" ? "active" : "")">
                            @Html.ActionLink("Przeglądaj produkty", "List", "Product")
                        </li>
                        <li>@Html.ActionLink("Dostawa", "InformationAboutDelivery", "DeliveryType")</li>
                        <li>@Html.ActionLink("Kontakt", "SendEmailForContact", "Home")</li>
                        <li>@Html.ActionLink("Rejestracja", "Register", "Client")</li>
                        <li>@Html.ActionLink("Zaloguj", "Login", "Client")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
        <div class="row panel Tlo">

            <div id="categories" class="col-xs-3">
                <br />
                @Html.Action("Menu", "ProductCategory")
            </div>

            <div class="col-lg-8">
                @RenderBody()
                <hr />
                <footer>
                    <p>&copy; @DateTime.Now.Year Gontek95</p>
                </footer>
            </div>
        </div>
</body>
</html>